export const UPDATE_COUNTRIES_RESULTS  = 'UPDATE_COUNTRIES_RESULTS';
export const UPDATE_SELECTED_RESULT = 'UPDATE_SELECTED_RESULT';
export const UPDATE_SELECTED_RESULTS = 'UPDATE_SELECTED_RESULTS';



